<?php

namespace Tabula17\Satelles\Nexus\Utilis\Server\Protocol\Response;

use Tabula17\Satelles\Nexus\Utilis\Exception\UnexpectedValueException;
use Tabula17\Satelles\Nexus\Utilis\Server\Protocol\Data\Stats;
use Tabula17\Satelles\Utilis\Collection\CallableCollection;
use Tabula17\Satelles\Utilis\Config\AbstractDescriptor;
use Tabula17\Satelles\Nexus\Utilis\Server\Protocol\Status;

abstract class Base extends AbstractDescriptor implements ResponseInterface
{
    /**
     * This property indicates where to store the id of the message to send back to the client.
     * If the client sends a message with an id, it will be stored in this property.
     * If it is null, the id will not be stored in the payload, but it will be generated and stored in the $id property of the Payload class.
     * This property must be defined in the Payload class and must be set to the name of an existing property where the ID will be stored.
     * @var string|null
     */
    abstract protected ?string $idProperty
        {
            get;
        }
    /**
     *
     * @var string|mixed
     */
    private string $_id
        {
            get {
                return $this->_id;
            }
            set(string $id) {
                $this->_id = $id;
                if (isset($this->idProperty) && $this->hasProperty($this->idProperty)) {
                    if(!isset($this->{$this->idProperty}) || $this->{$this->idProperty} !== $id) {
                        $this->set($this->idProperty, $id);
                    }
                }
                //$this->set($this->idProperty, $id);
            }
        }
    protected(set) string $action;
    protected(set) ?Stats $_metadata {
        set(Stats|array|null $stats) {
            $stats = $stats instanceof Stats ? $stats : new Stats(...$stats ?? []);
            $this->_metadata = $stats;
        }
    }
    abstract public AbstractDescriptor $response {
        get;
    }
    private CallableCollection $validators;
    private array $errors = [];
    private bool $validating = false;

    final public function __construct(
        public Status $status,
        ?array $values = []
    )
    {
        $this->validators = new CallableCollection();
        if (empty($values)) {
            $values = [];
        }
        $this->initialize($status, $values);
        parent::__construct($values);
        $prefix = strtolower($values['action'] ?? 'unknown') . '::';
        $this->_id = $values[$this->idProperty] ?? uniqid($prefix, true);
    }

    abstract public function initialize(Status $status, ?array &$values): void;

    public function addValidator(callable $validator): void
    {
        $this->validators->addIfNotExist($validator);
    }

    public function removeValidator(callable $validator): void
    {
        $this->validators->remove($validator);
    }
    public function getID(): string
    {
        return $this->_id;
    }
    /**
     * Determines if the current response passes all validation rules.
     *
     * @return bool True if all validators pass without errors, false otherwise.
     */
    final public function isValid(): bool
    {
        $this->validating = true;
        $this->errors = [];
        foreach ($this->validators as $validator) {
            $validate = $validator($this->response);
            if ($validate !== true) {
                $this->errors[] = $validate;
            }
        }
        $this->validating = false;
        return count($this->errors) === 0;
    }

    public function toArray(): array
    {
        if (!$this->validating && !$this->isValid()) {
            throw new UnexpectedValueException('Invalid response: *' . implode(PHP_EOL . '*', $this->errors));
        }
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

}