<?php

namespace Tabula17\Satelles\Nexus\Utilis\Server\Protocol\Response;

use Tabula17\Satelles\Nexus\Utilis\Exception\UnexpectedValueException;
use Tabula17\Satelles\Nexus\Utilis\Server\Protocol\Data\Stats;
use Tabula17\Satelles\Utilis\Collection\CallableCollection;
use Tabula17\Satelles\Utilis\Config\AbstractDescriptor;

abstract class Base extends AbstractDescriptor implements ResponseInterface
{
    protected(set) string $id;
    protected(set) string $action;
    protected(set) ?Stats $_metadata {
        set(Stats|array|null $stats) {
            $stats = $stats instanceof Stats? $stats:  new Stats(...$stats??[]);
            $this->_metadata = $stats;
        }
    }
    abstract AbstractDescriptor $response {
        get;
    }
    private CallableCollection $validators;
    private array $errors = [];
    private bool $validating = false;

    public function __construct(
        ?array $values = []
    )
    {
        $this->validators = new CallableCollection();
        if (empty($values)) {
            $values = [];
        }
        if (!isset($values['id'])) {
            $prefix = "nxs::" . strtolower($values['action'] ?? 'unknown') . '::';
            $values['id'] = uniqid($prefix, false);
        }
        parent::__construct($values);
    }

    public function addValidator(callable $validator): void
    {
        $this->validators->addIfNotExist($validator);
    }

    public function removeValidator(callable $validator): void
    {
        $this->validators->remove($validator);
    }

    /**
     * Determines if the current response passes all validation rules.
     *
     * @return bool True if all validators pass without errors, false otherwise.
     */
    final public function isValid(): bool
    {
        $this->validating = true;
        $this->errors = [];
        foreach ($this->validators as $validator) {
            $validate = $validator($this->response);
            if ($validate !== true) {
                $this->errors[] = $validate;
            }
        }
        $this->validating = false;
        return count($this->errors) === 0;
    }

    public function toArray(): array
    {
        if (!$this->validating && !$this->isValid()) {
            throw new UnexpectedValueException('Invalid response: *' . implode(PHP_EOL . '*', $this->errors));
        }
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

    public function fromPayload(mixed $payload): static
    {
        $self = clone $this;
        if (is_array($payload)) {
            $self->loadProperties($payload);
        }
        return $self;
    }

    public function __invoke($payload): mixed
    {
        return $this->fromPayload($payload);
    }
}