<?php

namespace Tabula17\Satelles\Nexus\Utilis\Connector\Database;

use mysqli;
use PDO;
use SQLite3;
use Swoole\Client;
use Tabula17\Satelles\Nexus\Utilis\Exception\ExceptionDefinitions;
use Tabula17\Satelles\Nexus\Utilis\Exception\InvalidArgumentException;
use Tabula17\Satelles\Utilis\Config\ConnectionConfig;

/**
 * Represents the configuration settings required for a database connection.
 *
 * This class encapsulates the details needed to establish a connection,
 * such as the database driver, host, port, credentials, and additional options.
 * It also provides functionality to validate connectivity and access configuration details.
 */
class DbConfig extends ConnectionConfig
{
    /**
     * The database driver used to establish the connection.
     * This can be either a string representing the driver name or an instance of DriversEnum.
     * @var DriversEnum $driver
     */
    protected(set) DriversEnum $driver {
        /**
         * @throws InvalidArgumentException
         */
        set(DriversEnum|string $driver) {
            if (is_string($driver)) {
                $driver = DriversEnum::fromName($driver);
            }
            if ($driver instanceof DriversEnum) {
                $this->driver = $driver;
            } else {
                throw new InvalidArgumentException(sprintf(ExceptionDefinitions::DATABASE_DRIVER_NOT_FOUND->value, $driver));
            }
        }
    }

    protected(set) bool $usePdo = false;
    protected(set) array $dsnOptions = [];
    public array $metadata = [];

    /**
     * Checks if a connection to the specified host and port can be established.
     *
     * @return bool Returns true if the connection is successful and the driver is available, otherwise false.
     */
    public function canConnect(): bool
    {
        if (!DriversEnum::isAvailable($this->driver)) {
            $driver = $this->driver->value ?? 'unknown';
            $this->lastConnectionError = "El driver para la conexión del tipo '$driver' no es válido o no está disponible.";
            return false;
        }
        return parent::canConnect();
    }

    public function setLastConnectionError(string $error): void
    {
        $this->lastConnectionError = $error;
    }

    public function setMetadataProperty(string $key, mixed $value): void
    {
        $this->metadata[$key] = $value;
    }

    public function unsetMetadataProperty(string $key): void
    {
        unset($this->metadata[$key]);
    }

    public function getSafeData(): array
    {
        $data = parent::getSafeData(); // TODO: Change the autogenerated stub
        $data['driver'] = $this->driver->value;
        return $data;
    }

    private function createPdoDsn(): string
    {
        $dsn = '';
        switch ($this->driver) {
            case DriversEnum::MYSQL:
                if ($this->unixSocket) {
                    $dsn = "mysql:unix_socket={$this->unixSocket}";
                } else {
                    $dsn = "mysql:host={$this->host}";
                    if (isset($this->port)) {
                        $dsn .= ";port={$this->port}";
                    }
                }
                if (isset($this->dbname)) {
                    $dsn .= ";dbname={$this->dbname}";
                }
                if (isset($this->charset)) {
                    $dsn .= ";charset={$this->charset}";
                }
                break;
            case DriversEnum::PGSQL:
                $dsn = "pgsql:host={$this->host}";
                if (isset($this->port)) {
                    $dsn .= ";port={$this->port}";
                }
                if (isset($this->dbname)) {
                    $dsn .= ";dbname={$this->dbname}";
                }
                break;
            case DriversEnum::SQLSRV:
                $dsn = "sqlsrv:Server={$this->host}";
                if (isset($this->port)) {
                    $dsn .= ",{$this->port}";
                }
                if (isset($this->dbname)) {
                    $dsn .= ";Database={$this->dbname}";
                }
                break;
            case DriversEnum::ORACLE:
                if ($this->unixSocket) {
                    $dsn = "oci:dbname=//{$this->unixSocket}";
                } else {
                    $host = $this->host;
                    if (isset($this->port)) {
                        $host .= ":{$this->port}";
                    }
                    $dsn = "oci:dbname={$host}";
                }
                if (isset($this->dbname)) {
                    $dsn .= "/{$this->dbname}";
                }
                if (isset($this->charset)) {
                    $dsn .= ";charset={$this->charset}";
                }
                break;
            case DriversEnum::SQLITE:
                $dsn = "sqlite:{$this->dbname}";
                break;
        }
        if (isset($this->dsnOptions)) {
            $dsn .= ';';
            foreach ($this->dsnOptions as $key => $value) {
                $dsn .= "{$key}={$value};";
            }
        }
        return $dsn;
    }

    private function getPdoConnection(): PDO
    {
        $dsn = $this->createPdoDsn();
        $arguments = [
            'dsn' => $dsn,
        ];
        if (isset($this->username)) {
            $arguments['username'] = $this->username;
        }
        if (isset($this->password)) {
            $arguments['password'] = $this->password;
        }
        if (isset($this->options)) {
            $arguments['options'] = $this->options;
        }

        return new PDO(...$arguments);
    }

    private function getNativeConnection(): mixed
    {
        switch ($this->driver->native()) {
            case 'mysqli':
                $arguments = [];
                if (isset($this->unixSocket)) {
                    $arguments['unix_socket'] = $this->unixSocket;
                }
                if (isset($this->host)) {
                    $arguments['host'] = $this->host;
                    if (isset($this->port)) {
                        $arguments['port'] = $this->port;
                    }
                }
                if (isset($this->dbname)) {
                    $arguments['dbname'] = $this->dbname;
                }
                if (isset($this->username)) {
                    $arguments['username'] = $this->username;
                }
                if (isset($this->password)) {
                    $arguments['password'] = $this->password;
                }
                if (isset($this->options)) {
                    $arguments['options'] = $this->options;
                }
                return new mysqli(...$arguments);
            case 'sqlsrv':
                $arguments = [];
                $server = $this->host;
                if (isset($this->port)) {
                    $server .= ",{$this->port}";
                }
                if (isset($this->dbname)) {
                    $arguments['Database'] = $this->dbname;
                }
                if (isset($this->username)) {
                    $arguments['UID'] = $this->username;
                }
                if (isset($this->password)) {
                    $arguments['PWD'] = $this->password;
                }
                if (isset($this->options)) {
                    $arguments['ConnectionOptions'] = $this->options;
                }
                if (isset($this->charset)) {
                    $arguments['CharacterSet'] = $this->charset;
                }
                return sqlsrv_connect($server, $arguments);
            case 'oci8':
                $arguments = [];
                if (isset($this->username)) {
                    $arguments['username'] = $this->username;
                }
                if (isset($this->password)) {
                    $arguments['password'] = $this->password;
                }
                $arguments['connection_string'] = $this->createPdoDsn();
                if (isset($this->charset)) {
                    $arguments['character_set'] = $this->charset;
                }
                return oci_connect(...$arguments);
            case 'sqlite':
                return new SQLite3($this->host);
            case 'pgsql':
                $arguments = [];
                if (isset($this->host)) {
                    $arguments['host'] = $this->host;
                }
                if (isset($this->port)) {
                    $arguments['port'] = $this->port;
                }
                if (isset($this->dbname)) {
                    $arguments['dbname'] = $this->dbname;
                }
                if (isset($this->username)) {
                    $arguments['user'] = $this->username;
                }
                if (isset($this->password)) {
                    $arguments['password'] = $this->password;
                }
                return pg_connect(http_build_query($arguments, '', ' '));
            default:
                return null;
        }
    }

    /**
     * @throws InvalidArgumentException
     */
    public function getDbConnector()
    {
        if ($this->usePdo) {
            if (!$this->driver->supportPdo()) {
                throw new InvalidArgumentException(sprintf(ExceptionDefinitions::DATABASE_DRIVER_NOT_SUPPORTED->value, $this->driver->value));
            }
            if (!$this->driver->supportNative()) {
                throw new InvalidArgumentException(sprintf(ExceptionDefinitions::DATABASE_DRIVER_NOT_SUPPORTED->value, $this->driver->value));
            }
            return $this->getPdoConnection();
        }
        return $this->getNativeConnection();
    }
}
/*
 *
        switch ($driver) {
            case 'sqlsrv':
                //$dsn = "sqlsrv:Server=your_server_name;Database=your_database_name";
                $host = [$this->config->getHost()];
                if ($this->config->getPort()) {
                    $host[] = $this->config->getPort();
                }
                $dsn = "sqlsrv:Server=" . implode(',', $host) . ";TrustServerCertificate=yes;Database=" . $this->config->getDbname();
                break;
            case 'mysql':
                if ($this->config->hasUnixSocket()) {
                    $dsn = "mysql:unix_socket={$this->config->getUnixSocket()};dbname={$this->config->getDbname()};charset={$this->config->getCharset()}";
                } else {
                    $dsn = "mysql:host={$this->config->getHost()};port={$this->config->getPort()};dbname={$this->config->getDbname()};charset={$this->config->getCharset()}";
                }
                break;
            case 'pgsql':
                $dsn = 'pgsql:host=' . ($this->config->hasUnixSocket() ? $this->config->getUnixSocket() : $this->config->getHost()) . ";port={$this->config->getPort()};dbname={$this->config->getDbname()}";
                break;
            case 'oci':
                $dsn = 'oci:dbname=' . ($this->config->hasUnixSocket() ? $this->config->getUnixSocket() : $this->config->getHost()) . ':' . $this->config->getPort() . '/' . $this->config->getDbname() . ';charset=' . $this->config->getCharset();
                break;
            case 'sqlite':
                // There are three types of SQLite databases: databases on disk, databases in memory, and temporary
                // databases (which are deleted when the connections are closed). It doesn't make sense to use
                // connection pool for the latter two types of databases, because each connection connects to a
                //different in-memory or temporary SQLite database.
                if ($this->config->getDbname() === '') {
                    throw new RuntimeException('Connection pool in Swoole does not support temporary SQLite databases.');
                }
                if ($this->config->getDbname() === ':memory:') {
                    throw new RuntimeException('Connection pool in Swoole does not support creating SQLite databases in memory.');
                }
                $dsn = 'sqlite:' . $this->config->getDbname();
                break;
            default:
                throw new RuntimeException('Unsupported Database Driver:' . $driver);
        }
 */